### ISSUE TITLE
Provide Binaries For Darwin ARM64

### ISSUE THREAD

**Issue by seanmalloy** [KohlsTechnology/blackbox-helloworld-responder#86]
## What happens?

This project does not provide officially released binaries for Darwin ARM64(i.e. Apple Silicon).

## What were you expecting to happen?

Darwin ARM64 binaries are provided on the releases page.

## Steps to reproduce: 

Open the releases page and notice that Darwin ARM64 binaries are provided.

## Any errors, stacktrace, logs? 

N/A

## Environment:

N/A

## Additional comments:

N/A

**Comment by vinny-sabatini** [comment]
Re-opening this to make sure this works with a release. Will close it after I verify it worked.

**Comment by vinny-sabatini** [comment]
Release [v0.1.20](https://github.com/KohlsTechnology/blackbox-helloworld-responder/releases/tag/v0.1.20) provided the first arm64 binaries for this project
